Affected Issue(s): #114
What this commit has achieved:
1. Test revert to `CREATE OR REPLACE` due to
```
ERROR:  cannot drop view generated_views."Observation_all_versions_view" because other objects depend on it
```