Affected Issue(s): Error
What this commit has achieved:
1. NOTICE:  view "z_flattened_AllergyIntolerance_all_versions_view" does not exist, skipping
ERROR:  too few arguments for format()